#docker-compose.yml
version: '2'
services:
    #WEB
    web:
        container_name: web-static
        build: ./site
        environment:
            PORT: 3000
            API_HOST: 'hostapi'
            API_PORT: 4000
        ports:
            - 80:80
        depends_on:
            - api-host
        volumes:
            - ./site:/home/site
            - /home/site/node_modules
    #API
    api-host:
        container_name: api-host
        build: ./api
        links:
            - db
        environment:
            PORT: 4000
        ports:
            - "4000:4000"
        volumes:
            - ./api:/home/api
            - /home/api/node_modules
    #MySQL
    db:
        image: mysql:5.7
        ports:
          - "3310:3306"
        container_name: developers-mysql
        environment:
          - MYSQL_ROOT_PASSWORD=melhoridade
          - MYSQL_DATABASE=melhoridade
          - MYSQL_USER=melhoridade
          - MYSQL_PASSWORD=melhoridade