version: '2'
services:
    #WEBSITE
    web:
        container_name: web-static
        build: ./site
        environment:
            PORT: 3000
            API_HOST: 'hostapi'
            API_PORT: 4000
        ports:
            - 3000:3000
        depends_on:
            - hostapi
        volumes:
            - ./site:/home/site
            - /home/site/node_modules
    #API
    hostapi:
        container_name: host-api
        build: ./api
        links:
            - db
        environment:
            PORT: 4000
        volumes:
            - ./api:/home/api
            - /home/api/node_modules
    #MYSQL
    db:
        image: mysql:5.7
        ports:
            - "3310:3306"
        container_name: developers-mysql
        environment:
          - MYSQL_ROOT_PASSWORD=melhoridade
          - MYSQL_DATABASE=melhoridade
          - MYSQL_USER=melhoridade
          - MYSQL_PASSWORD=melhoridade
        